# Generated by Django 4.2.16 on 2024-11-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bank_details_gbp', models.JSONField(blank=True, null=True)),
                ('bank_details_eur', models.JSONField(blank=True, null=True)),
                ('bank_details_usd', models.JSONField(blank=True, null=True)),
                ('bank_details_inr', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
