# Generated by Django 4.2.16 on 2024-11-08 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_gbp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_inr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
