# Generated by Django 4.2.16 on 2024-11-08 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_currency', models.CharField(max_length=3)),
                ('buy_currency', models.CharField(max_length=3)),
                ('amount_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_bought', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
