# Generated by Django 4.2.16 on 2024-11-15 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default='NOT AVAILABLE', max_length=255)),
                ('bank_name', models.CharField(default='NOT AVAILABLE', max_length=255)),
                ('bank_address', models.TextField(default='NOT AVAILABLE')),
                ('iban', models.CharField(default='NOT AVAILABLE', max_length=34)),
                ('sort_code', models.CharField(default='NOT AVAILABLE', max_length=10)),
                ('clearing_code', models.CharField(default='NOT AVAILABLE', max_length=20)),
                ('bic_code', models.CharField(default='NOT AVAILABLE', max_length=11)),
                ('account_number', models.CharField(default='NOT AVAILABLE', max_length=20)),
                ('ifsc', models.CharField(default='NOT AVAILABLE', max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
